### ISSUE TITLE
How to set the process exit code ?

### ISSUE THREAD

**Issue by eloyleonardo** [anseki/gulp-confirm#3]
If the tasks where aborted the process exit with code 0. How can i change that ? 
This can be a problem if you have a external tool calling the script, it can't know if the process exit successfully or was aborted.

**Comment by anseki** [comment]
Hi @eloyleonardo, thank you for the comment.

The Gulp controls a process, not the plug-in. The plug-in only controls aborting the tasks.
Then, you can use [`proceed`](https://github.com/anseki/gulp-confirm#proceed) option to do anything with the `process`.
For example, the process is exited with code `1` when you press a key other than `Y` key:

```js
confirm({
  question: 'Continue?',
  input: '_key',
  proceed: answer => {
    if (answer.toLowerCase() !== 'y') {
      console.error('The process is exited with code `1`.');
      process.exit(1);
    }
    return true;
  }
})
```

**Comment by eloyleonardo** [comment]
Ohh taught that will be a option to the library to that.
This way works very well. 
Thank you for the answer

**Comment by anseki** [comment]
😄
